M48
; DRILL file {KiCad 7.0.6} date Sun Nov 19 20:23:39 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-19T20:23:39+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0906
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.3967Y-4.2021
X4.3967Y-5.2257
T2
X2.3396Y-3.6292
X2.3396Y-4.7749
X3.937Y-3.1496
X3.937Y-5.2545
T0
M30
