M48
; DRILL file {KiCad 7.0.6} date Sun Feb 11 15:29:09 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-11T15:29:09+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0906
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.389Y-2.6194
X7.4126Y-2.6194
T2
X6.263Y-2.4016
X6.263Y-4.3701
X7.5386Y-2.4016
X7.5386Y-4.3701
T0
M30
