M48
; DRILL file {KiCad 8.0.1} date 2024-09-24T23:40:50+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-24T23:40:50+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X0.0Y0.0
X0.0Y-0.1
X0.0Y-0.2
X0.3Y0.0
X0.3Y-0.1
X0.3Y-0.2
X0.4Y0.0
X0.4Y-0.1
X0.4Y-0.2
X0.7Y0.0
X0.7Y-0.1
X0.7Y-0.2
M30
